#!/usr/bin/env python3
"""Regenerate src/vz/Levels.java from the maps produced by mapgen.py.

Run from the repository root:  python3 tools/mklevels.py
The generator is deterministic, so the committed Levels.java can always be
reproduced, and every map it emits is validated before it is written.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mapgen

NAMES = ["DOCKING RING", "HYDROPONICS", "REACTOR SPINE", "COMMAND BRIDGE"]
# 0 = reach the exit, 1 = destroy the reactor nodes, 2 = kill the guardian
OBJECTIVES = [0, 1, 0, 2]
START_ANGLES = [1536, 1536, 1536, 1536]
SEEDS = [2100, 2101, 2102, 2103]

SOLID = set("#%=&")
LEGEND = set("#%=&.DRGBrgbPEdthXTmaipWQ")
DOOR_KEYS = {"R": 1, "G": 2, "B": 4}
KEYS = {"r": 1, "g": 2, "b": 4}


def validate(name, rows):
    w, h = len(rows[0]), len(rows)
    problems = []
    if w > 32 or h > 32:
        problems.append("larger than the 32x32 grid")
    for y, row in enumerate(rows):
        if len(row) != w:
            problems.append("row %d has width %d, expected %d" % (y, len(row), w))
        for x, c in enumerate(row):
            if c not in LEGEND:
                problems.append("row %d has illegal character %r" % (y, c))
            if (y in (0, h - 1) or x in (0, w - 1)) and c not in SOLID:
                problems.append("border hole at %d,%d" % (x, y))
    counts = collections.Counter("".join(rows))
    if counts["P"] != 1:
        problems.append("expected one start, found %d" % counts["P"])
    if counts["E"] != 1:
        problems.append("expected one exit, found %d" % counts["E"])

    start = next((x, y) for y, row in enumerate(rows)
                 for x, c in enumerate(row) if c == "P")
    exit_cell = next((x, y) for y, row in enumerate(rows)
                     for x, c in enumerate(row) if c == "E")

    def flood(keys):
        seen = {start}
        q = collections.deque([start])
        while q:
            x, y = q.popleft()
            for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                if not (0 <= nx < w and 0 <= ny < h) or (nx, ny) in seen:
                    continue
                c = rows[ny][nx]
                if c in SOLID:
                    continue
                if c in DOOR_KEYS and not keys & DOOR_KEYS[c]:
                    continue
                seen.add((nx, ny))
                q.append((nx, ny))
        return seen

    keys = 0
    for _ in range(4):
        area = flood(keys)
        got = 0
        for (x, y) in area:
            c = rows[y][x]
            if c in KEYS:
                got |= KEYS[c]
        if got == keys:
            break
        keys |= got
    area = flood(keys)
    if exit_cell not in area:
        problems.append("the exit cannot be reached even with every keycard")
    if any(DOOR_KEYS.get(rows[y][x]) for y in range(h) for x in range(w)):
        if exit_cell in flood(0):
            problems.append("the locked doors do not actually gate the exit")
    stranded = [(x, y, rows[y][x]) for y in range(h) for x in range(w)
                if rows[y][x] not in SOLID and (x, y) not in area]
    if stranded:
        problems.append("%d unreachable cells, first %s" % (len(stranded), stranded[0]))
    return problems, counts


def main():
    maps = []
    for i, spec in enumerate(mapgen.SPECS):
        rows = mapgen.build(spec, SEEDS[i])
        problems, counts = validate(spec["name"], rows)
        if problems:
            for msg in problems:
                print("%s: %s" % (spec["name"], msg), file=sys.stderr)
            return 1
        contents = dict((k, v) for k, v in sorted(counts.items())
                        if k not in SOLID and k != ".")
        print("%s %dx%d %s" % (spec["name"], len(rows[0]), len(rows), contents))
        maps.append(rows)

    out = []
    out.append("package vz;")
    out.append("")
    out.append("/**")
    out.append(" * Level data. Generated by tools/mklevels.py, which guarantees that every")
    out.append(" * level is completable: each locked door is the only way into the sector")
    out.append(" * behind it and its keycard always lies in an earlier sector.")
    out.append(" *")
    out.append(" * Legend:")
    out.append(" *   # % = &  walls (metal, tech, vent, hull)     .  floor")
    out.append(" *   D        door                                R G B  locked doors")
    out.append(" *   r g b    keycards                            P  start       E  exit")
    out.append(" *   d t h X  drone, trooper, heavy, guardian     T  reactor node")
    out.append(" *   m a      medkit, armour                      i p  rifle / plasma ammo")
    out.append(" *   W Q      rifle, plasma gun")
    out.append(" *")
    out.append(" * MIDP free.")
    out.append(" */")
    out.append("public final class Levels {")
    out.append("")
    out.append("    public static final int COUNT = %d;" % len(maps))
    out.append("")
    out.append("    public static final int OBJ_EXIT = 0;")
    out.append("    public static final int OBJ_NODES = 1;")
    out.append("    public static final int OBJ_BOSS = 2;")
    out.append("")
    out.append("    public static final String[] NAME = {")
    for n in NAMES:
        out.append('        "%s",' % n)
    out.append("    };")
    out.append("")
    out.append("    public static final int[] OBJECTIVE = { %s };"
               % ", ".join(str(o) for o in OBJECTIVES))
    out.append("")
    out.append("    public static final int[] START_ANGLE = { %s };"
               % ", ".join(str(a) for a in START_ANGLES))
    out.append("")
    out.append("    public static final String[][] MAPS = {")
    for i, rows in enumerate(maps):
        out.append("        // %s  %dx%d" % (NAMES[i], len(rows[0]), len(rows)))
        out.append("        {")
        for r in rows:
            out.append('            "%s",' % r)
        out.append("        },")
    out.append("    };")
    out.append("")
    out.append("    private Levels() {")
    out.append("    }")
    out.append("}")

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                        "src", "vz", "Levels.java")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s" % os.path.normpath(path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
